# Generated by Django 5.2.7 on 2025-11-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('mail_id', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('designation', models.CharField(max_length=70, verbose_name='Designation')),
                ('qualification', models.CharField(max_length=255, verbose_name='Highest Qualification')),
                ('experience', models.IntegerField(default=0, verbose_name='Years of Experience')),
                ('gender', models.CharField(max_length=6, verbose_name='Gender')),
            ],
            options={
                'verbose_name_plural': 'Faculty',
                'ordering': ['name'],
            },
        ),
    ]
