# Generated by Django 5.2.7 on 2025-11-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
