# Generated by Django 5.2.7 on 2025-11-26 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('puc1', 'PUC 1'), ('puc2', 'PUC 2'), ('e1', 'E1'), ('e2', 'E2'), ('e3', 'E3'), ('e4', 'E4')], max_length=4, verbose_name='Academic Year')),
                ('sem', models.CharField(choices=[('sem1', 'Semester 1'), ('sem2', 'Semester 2')], max_length=4, verbose_name='Semester')),
                ('class_name', models.CharField(max_length=20, verbose_name='Class/Section Name')),
                ('verified', models.BooleanField(default=False)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty', to_field='mail_id', verbose_name='Faculty In-Charge')),
            ],
        ),
    ]
