# Generated by Django 5.2.7 on 2025-11-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_classdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdetails',
            name='verified',
        ),
    ]
