# Generated by Django 5.2.7 on 2025-12-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_remove_classdetails_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetails',
            name='subject',
            field=models.CharField(default=1, max_length=100, verbose_name='Subject Name'),
            preserve_default=False,
        ),
    ]
