# Generated by Django 5.1.6 on 2025-09-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='blood_group',
            new_name='bloodGroup',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='father_name',
            new_name='fatherName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='hall_ticket_no',
            new_name='hallTicketNo',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='hostel_name',
            new_name='hostelName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='id_no',
            new_name='idNo',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mother_name',
            new_name='motherName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='parent_phone_number',
            new_name='parentMobile',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='year',
            new_name='rollNo',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='room_no',
            new_name='roomNo',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_year',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phone_number',
            new_name='studentMobile',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=6),
        ),
    ]
