# Generated by Django 5.1.6 on 2025-09-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_blood_group_student_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default=21, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='gmail',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='idNo',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
