# Generated by Django 5.2.7 on 2025-10-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_batch_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_temp',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('rollNo', models.IntegerField()),
                ('gmail', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('idNo', models.CharField(max_length=7, unique=True)),
                ('section', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6)),
                ('branch', models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], max_length=5)),
                ('fatherName', models.CharField(blank=True, max_length=100)),
                ('motherName', models.CharField(blank=True, max_length=100)),
                ('hallTicketNo', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('studentMobile', models.CharField(max_length=10)),
                ('parentMobile', models.CharField(blank=True, max_length=10)),
                ('guardian', models.BooleanField(default=False)),
                ('batch', models.CharField(max_length=3)),
                ('hostelName', models.CharField(blank=True, max_length=100)),
                ('roomNo', models.CharField(blank=True, max_length=10)),
                ('bloodGroup', models.CharField(blank=True, max_length=5)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('HOD', 'HOD'), ('AO', 'AO'), ('DEAN', 'Dean'), ('DSW', 'DSW'), ('DIRECTOR', 'Director'), ('ADMIN', 'Admin')], default='Student', max_length=10, verbose_name='user role'),
        ),
    ]
