# Generated by Django 5.2.7 on 2025-10-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_temp_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
