# Generated by Django 5.2.7 on 2025-11-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('mail_id', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('designation', models.CharField(max_length=70, verbose_name='Designation')),
                ('qualification', models.CharField(max_length=255, verbose_name='Highest Qualification')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Years of Experience')),
            ],
            options={
                'verbose_name_plural': 'Faculty',
                'ordering': ['name'],
            },
        ),
    ]
