# Generated by Django 5.2.7 on 2025-11-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='gender',
            field=models.CharField(default=1, max_length=6, verbose_name='MALE of FEMALE'),
            preserve_default=False,
        ),
    ]
