# Generated by Django 5.2.7 on 2025-11-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_faculty_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
