# Generated by Django 5.2.7 on 2025-12-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_delete_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
