# Generated by Django 5.2.7 on 2025-12-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
