# Generated by Django 5.2.7 on 2025-12-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_student_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('HOD', 'HOD'), ('AO', 'AO'), ('DEAN', 'Dean'), ('DSW', 'DSW'), ('DIRECTOR', 'Director'), ('ADMIN', 'Admin')], max_length=10, verbose_name='user role'),
        ),
        migrations.AlterField(
            model_name='student_temp',
            name='guardian',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
