# Generated by Django 5.2.7 on 2025-12-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_customuser_role_alter_student_temp_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_temp',
            name='dob',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
