# Generated by Django 5.2.7 on 2025-12-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_student_temp_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_temp',
        ),
        migrations.AddField(
            model_name='student',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
